spring:
  profiles:
    active: dev
    include: druid,security
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  session:
    timeout: 1800
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true